# Site settings
username: Rick
title: Rick's World
description: 每个人，都有一个环游世界的梦
email: acxin2011@gmail.com
url: https://acxin2011.github.io
baseurl: /photo

# Internal nav
nav:
  - GALLERY: "gallery"
  # - TUTORIAL: "tutorial"
  # - ABOUT: "about"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/tutorial/page:num/"
permalink: "/tutorial/:title/"
gems:
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
