# Site settings
username: whatwhyhow7
title: Hower Vision
description: 那些年 到过的远方，写过的诗，拍过的人们，还有故事
email: wangwenhao.rar@gmail.com
url: https://whatwhyhow7.github.io
baseurl: /photo

# Internal nav
nav:
  - GALLERY: "gallery"
  # - TUTORIAL: "tutorial"
  # - ABOUT: "about"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/tutorial/page:num/"
permalink: "/tutorial/:title/"
gems:
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"